### PR TITLE
Replace gateway apis v1beta1 with v1 apis

### LINKED ISSUE #687: Update to Gateway v1 APIs
I'm debating if we should do this - I think most implementations will support v1beta1 for a while. But I think all the ones we test with now support v1.

/assign @izabelacg

### PR DESCRIPTION
**Pull request by izabelacg**
# Changes
- replaces gateways apis v1beta1 with v1 apis (Gateway, HTTPRoute)
- PS: ReferenceGrant is still in beta

Fixes #687

### CODE REVIEW

**Comment by nader-ziada** [comment]
lgtm

**Comment by dprotaso** [comment]
/lgtm
/approve

woot `v1`

**Comment by dprotaso** [comment]
tide/prow is broken and blocking PRs because some GitHub Actions were skipped - this isn't normal

/override "Generate some code!"

**Pull request merged**
