### PR TITLE
add the port name used by contour in lister matching

### LINKED ISSUE #639: Contour continuous tests are pretty flakey
https://testgrid.k8s.io/r/knative-own-testgrid/net-gateway-api#continuous-contour

Screenshot 2024-03-05 at 3 38 12 PM

### PR DESCRIPTION
**Pull request by nader-ziada**
# Changes

- add the port name used by contour so lister can match on and find the correct port

/kind :bug: 

Fixes #639

### CODE REVIEW

**Comment by izabelacg** [comment]
I don't think I can approve, but let's try 😆 

/approve

**Review by dprotaso — APPROVED** [review]
/lgtm
/approve

@nader-ziada can you create a follow up issue in this repo - we need a general way of solving this that isn't specific to an implementation.

eg. maybe in this code we need to look at the K8s Service and not the endpoint

**Comment by nader-ziada** [comment]
added issue as followup https://github.com/knative-extensions/net-gateway-api/issues/668

**Pull request merged**
