### PR TITLE
Propagate HostRewrite from Knative Ingress to HttpRoute

### LINKED ISSUE #533: Add HostRewrite Support
The Gateway API has a HostRewrite extended feature that Contour and Istio both support.

https://gateway-api.sigs.k8s.io/references/spec/#gateway.networking.k8s.io/v1beta1.HTTPRouteFilter

Our Knative Ingress resource has a similar functionality for rewriting the `Host` header - it's used to implement DomainMapping.

https://github.com/knative/networking/blob/e3c3201da0e301605b5fac8d81700fadb351fa60/pkg/apis/networking/v1alpha1/ingress_types.go#L212

What's missing in our `net-gateway-api` controller is propagating the KIngress `RewriteHost` value when creating the Gateway's HTTPRoute  resource.

### PR DESCRIPTION
**Pull request by andrew-su**
# Changes

- Propagate `HostRewrite` from Knative Ingress to `HttpRoute`

/kind enhancement

Fixes #533

### CODE REVIEW

**Review by KauzClay — APPROVED** [review]

**Review by nak3 — CHANGES_REQUESTED** [review]
Thank you so much!

Could you update `hack/test-env.sh` to run `host-rewrite` test?

TOBE in `hack/test-env.sh`:
```
export ISTIO_UNSUPPORTED_E2E_TESTS="retry,httpoption"
```

Then, please run `hack/update-codegen.sh`.

Note, I tested it on Contour but the `host-rewrite` conformance test didn't work for Contour. (It works for Istio so this PR should have no problem.)
Maybe https://github.com/knative-extensions/net-gateway-api/issues/536 is related?

**Comment by nak3** [comment]
/lgtm
/approve

Thank you so much!

**Comment by dprotaso** [comment]
Contour v1.26 supports HostRewrite - https://github.com/kubernetes-sigs/gateway-api/blob/d4ff2d4f07ce47222a4f97296618dbb09b2538dd/conformance/reports/v0.8.0/projectcontour-contour.yaml#L35C7-L35C27

**Pull request merged**
