### PR TITLE
Add gateway api crds file to release

### LINKED ISSUE #539: net-gateway-api shouldn't re-release Gateway API CRDs
We shouldn't be shipping the Gateway API CRDs

https://github.com/knative-extensions/net-gateway-api/blob/main/config/100-gateway-api.yaml

In places where we need to install Gateway API we should probably use similar steps as istio outlines

https://istio.io/latest/docs/tasks/traffic-management/ingress/gateway-api/#setup

```sh
kubectl get crd gateways.gateway.networking.k8s.io &> /dev/null || \
  { kubectl kustomize "github.com/kubernetes-sigs/gateway-api/config/crd?ref=v0.8.0-rc1" | kubectl apply -f -; }
```

We'll want to update our docs as well

### PR DESCRIPTION
**Pull request by gabo1208**
# Changes

- 🧹 Add gateway api crds file to release

/kind cleanup

Fixes #539

### CODE REVIEW

**Comment by nak3** [comment]
@gabo1208 Thank you! Could you please rebase this?
Also, once this merged, we need to change https://github.com/knative-extensions/knobots/blob/9a95f1f863feff2231e07a3912a37c4e0210c506/.github/workflows/update-nightlies.yaml#L87 (you might already know about it, though.)

**Comment by gabo1208** [comment]
Didn't knew that! I'm still navigating the whole Serving experience 😄 ! Thank you @nak3 

PR done here: https://github.com/knative-extensions/knobots/pull/344

**Comment by nak3** [comment]
/lgtm

Thank you!

**Pull request merged**
